name: game_fossilquest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
    - family: League Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-VariableFont.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont.ttf
