final List<String> blankFossil = [
  '../../assets/images/fossilblank/daun_blank.png',
  '../../assets/images/fossilblank/ikan_blank.png',
  '../../assets/images/fossilblank/kepala_blank.png',
  '../../assets/images/fossilblank/kerang_blank.png',
  '../../assets/images/fossilblank/mosasaurus_blank.png',
  '../../assets/images/fossilblank/ornithopoda_blank.png',
  '../../assets/images/fossilblank/pteranodon_blank.png',
  '../../assets/images/fossilblank/theropoda_blank.png',
  '../../assets/images/fossilblank/triceratops_blank.png',
  '../../assets/images/fossilblank/tulang_blank.png',
  '../../assets/images/fossilblank/tylosaurus_blank.png',
  '../../assets/images/fossilblank/tyrannosaurus_blank.png',
  '../../assets/images/fossilblank/velociraptor_blank.png',
];
